import { Maven_Pro } from "next/font/google";
import "./globals.css";
import GlobalState from "@/context";
import Navbar from "@/components/navbar";

const maven_pro = Maven_Pro({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Walk Wardrobe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={maven_pro.className}>
        <GlobalState>
          <Navbar />
          <main className="flex min-h-screen flex-col mt-[75px]">
            {children}
          </main>
        </GlobalState>
      </body>
    </html>
  );
}
